[env]
DATABASE_URL = { script = ["sed s/DATABASE_URL=// .env.test"] }
RUST_BACKTRACE = "0"

[tasks.resetdb]
command = "diesel"
args = ["database", "reset"]

[tasks.test]
dependencies = ["resetdb"]
command = "cargo"
args = ["test"]